Repository hyprutils/hyprgui, pull requests merged in 2024-10, with the labels that each got.

#5 feat: a desktop entry + readme update
  hyprgui.desktop
  readme.md
Labels: enhancement

#16 fix a typo in the CI
  .github/workflows/rust.yml
Labels: bug

#18 better GitHub auto-generated release notes
  .github/release.yml
Labels: documentation

#20 Fix position reset
  .github/preview.png
  src/gui.rs
Labels: bug

#23 Add more sections e.g. debug cursor render
  .github/preview.png
  src/gui.rs
Labels: enhancement

#24 Implement Min max values
  src/gui.rs
Labels: enhancement

#25 use prefixes for nested configuration options
  src/gui.rs
Labels: bug

#26 Cap tab names
  .github/preview.png
  src/gui.rs
Labels: enhancement

#27 Better error handling
  src/gui.rs
  src/main.rs
Labels: enhancement

#28 Add more default values
  src/gui.rs
Labels: enhancement

#29 Use string instead of int
  src/gui.rs
Labels: bug

#31 Implement GUI configs
  Cargo.lock
  Cargo.toml
  src/gui.rs
  src/main.rs
Labels: enhancement

#32 implement Undo functionality
  src/gui.rs
  src/main.rs
Labels: enhancement

#35 fix undo functionality
  src/gui.rs
  src/main.rs
Labels: bug

#36 fix color formatting
  src/gui.rs
Labels: bug

#38 add values to descriptions
  src/gui.rs
Labels: enhancement

#39 optimize binary size
  Cargo.lock
  Cargo.toml
Labels: enhancement

#40 feat: add a `Copyright` button
  src/main.rs
Labels: enhancement

#46 docs: more release labels
  .github/release.yml
Labels: documentation

#48 fix: github release notes not working
  .github/release.yml
Labels: documentation

#49 org updates
  .github/CODEOWNERS
  readme.md
  src/main.rs
Labels: documentation

#53 refact: update `hyprparser`
  Cargo.lock
  Cargo.toml
Labels: refactor
