Repository hyprutils/hyprgui, pull requests merged in 2024-11, with the labels that each got.

#57 add support for sourced files
  src/gui.rs
  src/main.rs
Labels: enhancement, rust, refactor

#58 V0.1.6
  Cargo.lock
  Cargo.toml
Labels: rust

#59 fix clippy
  src/gui.rs
Labels: rust, refactor

#62 close popover when button is pressed
  src/gui.rs
  src/main.rs
Labels: rust, refactor

#63 remove unnecessary button
  src/gui.rs
Labels: rust, refactor

#64 feat: search
  src/gui.rs
  src/main.rs
Labels: enhancement, rust

#65 fix gear button functionality
  src/gui.rs
Labels: bug, rust

#66 v0.1.7
  Cargo.lock
  Cargo.toml
Labels: enhancement, rust

#67 bump hyprparser
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#69 update preview
  .github/preview.png
  readme.md
Labels: documentation

#70 docs: add a repology badge & nix install instructions
  readme.md
Labels: documentation

#72 move all module related code to a separate file(s)
  src/gui.rs
  src/main.rs
  src/modules.rs
  src/widgets.rs
Labels: rust, refactor

#73 bump hyprparser
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust

#76 fix incorrect repo
  Cargo.toml
Labels: dependencies, rust

#80 Choose config file
  src/main.rs
Labels: enhancement, rust

#82 v0.1.8
  Cargo.toml
Labels: rust

#85 replace allow dumb copy
  src/modules.rs
Labels: rust, refactor

#91 add missing modules
  src/modules.rs
Labels: enhancement, rust

#92 docs: add the Grind badge
  readme.md
Labels: documentation
